version: '3.4'
services:
  #consoleapp_dockerwithkafka:
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "confluentinc/cp-kafka"